// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type TransactionEntryType string

const (
	TransactionEntryTypeInbound  TransactionEntryType = "inbound"
	TransactionEntryTypeOutbound TransactionEntryType = "outbound"
)

func (e *TransactionEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionEntryType(s)
	case string:
		*e = TransactionEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionEntryType: %T", src)
	}
	return nil
}

type NullTransactionEntryType struct {
	TransactionEntryType TransactionEntryType
	Valid                bool // Valid is true if TransactionEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionEntryType), nil
}

type TransactionType string

const (
	TransactionTypeDeposit  TransactionType = "deposit"
	TransactionTypeTransfer TransactionType = "transfer"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type WalletType string

const (
	WalletTypeSeller WalletType = "seller"
	WalletTypeCommom WalletType = "commom"
)

func (e *WalletType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WalletType(s)
	case string:
		*e = WalletType(s)
	default:
		return fmt.Errorf("unsupported scan type for WalletType: %T", src)
	}
	return nil
}

type NullWalletType struct {
	WalletType WalletType
	Valid      bool // Valid is true if WalletType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWalletType) Scan(value interface{}) error {
	if value == nil {
		ns.WalletType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WalletType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWalletType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WalletType), nil
}

type Transaction struct {
	ID          uuid.UUID
	ReferenceID uuid.UUID
	WalletID    uuid.UUID
	Type        TransactionType
	EntriesType TransactionEntryType
	Currency    string
	Amount      int32
	Timestamp   time.Time
	Snapshot    uuid.NullUUID
}

type Wallet struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CustomerName    string
	DocumentNumber  string
	WalletType      WalletType
	Email           string
	EncodedPassword string
	PhoneNumber     string
}
