// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetTransactionByWalletID(ctx context.Context, walletID uuid.UUID) ([]Transaction, error)
	GetWalletByID(ctx context.Context, id uuid.UUID) ([]GetWalletByIDRow, error)
	SaveTransaction(ctx context.Context, arg SaveTransactionParams) error
	SaveWallet(ctx context.Context, arg SaveWalletParams) error
}

var _ Querier = (*Queries)(nil)
